/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegodeteclas;

import java.util.TimerTask;
import java.util.Timer;
import javax.swing.JOptionPane;

/**
 *
 * @author Méndez Almada
 */
public class ventana extends javax.swing.JFrame {
    //Declaramos algunas variables globales para el uso durante toda la ejecución del juego
     int aleatorio;
     int aciertos = 0;
     int intentos = 3;
     char teclaSorteada;
     
     
     int IntervaloDeTiempo = 1000;
     int TiempoRestante = 60;
     char[] arrayDeTeclas = {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T',
        'U', 'V', 'W', 'X', 'Y', 'Z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9'};
    /**
     * Creates new form ventana
     */
    public void sortear() {
        lblTiempo.setText(TiempoRestante + "");
        aleatorio = (int) (Math.random() * arrayDeTeclas.length);
        //Seleccionamos el caracter sorteado
        teclaSorteada = arrayDeTeclas[aleatorio];
        System.out.println(teclaSorteada);
        lblTecla.setText(Character.toString(teclaSorteada));
       
        
    }
    //constructor de la ventana
    public ventana() {
        initComponents();
        //Luego de inicializar todos los componentes gráficos, tenemos que hacer algunas cuentas
       
        //Posicionamos el label con la tecla a presionar, encima del label que contiene la imagen
        lblTecla.setLocation(390, 192);
        getContentPane().setComponentZOrder(this.lblTecla, 0); 
       //Este timer se ejecuta por cada intervalo de tiempo definido en las variables globales
        new Timer().scheduleAtFixedRate(new TimerTask(){
            @Override
            public void run(){
                //Si nos queda tiempo restante o intentos, generamos otra tecla aleatoria y lo mostramos
                if((TiempoRestante > -1) && (intentos > 0)) {
                        sortear();
                } else {
                    //Si se terminó el juego, tenemos que parar el juego
                    this.cancel();
                    JOptionPane.showMessageDialog(null, "GAME OVER, terminaste con "+aciertos+" aciertos y "+intentos+" intentos");
                }
            }
        },0,IntervaloDeTiempo);
        
        //usamos otro timer que se ejecute cada 1000ms (1  segundo) para restar al tiempo de juego
        new Timer().scheduleAtFixedRate(new TimerTask(){
            @Override
            public void run(){
              TiempoRestante--;
              lblTiempo.setText(TiempoRestante+"");
            }
        },0,1000);
          
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTecla = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblAciertos = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblIntentos = new javax.swing.JLabel();
        lblTeclaPresionada = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblrestante = new javax.swing.JLabel();
        lblTiempo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        lblTecla.setFont(new java.awt.Font("Times New Roman", 1, 110)); // NOI18N
        lblTecla.setText("A");
        lblTecla.setToolTipText("");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tecla2.png"))); // NOI18N
        jLabel6.setLabelFor(lblTecla);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(876, 876, 876)
                    .addComponent(lblTecla)
                    .addContainerGap(877, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(155, 155, 155)
                    .addComponent(lblTecla)
                    .addContainerGap(155, Short.MAX_VALUE)))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Presiona  la Tecla");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 0));
        jLabel2.setText("Aciertos: ");

        lblAciertos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblAciertos.setForeground(new java.awt.Color(51, 153, 0));
        lblAciertos.setText("0");
        lblAciertos.setName("lblAciertos"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 153, 0));
        jLabel4.setText("Intentos Restantes: ");

        lblIntentos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblIntentos.setForeground(new java.awt.Color(51, 153, 0));
        lblIntentos.setText("3");
        lblIntentos.setName("lblIntentos"); // NOI18N

        lblTeclaPresionada.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTeclaPresionada.setText("(nada aún)");
        lblTeclaPresionada.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Presionaste");

        lblrestante.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblrestante.setForeground(new java.awt.Color(204, 0, 0));
        lblrestante.setText("Tiempo restante:");

        lblTiempo.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblTiempo.setForeground(new java.awt.Color(204, 0, 0));
        lblTiempo.setText("60");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 58, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAciertos, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblrestante, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lblIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(lblTeclaPresionada)
                .addGap(424, 424, 424))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(537, Short.MAX_VALUE)
                    .addComponent(lblTiempo)
                    .addGap(372, 372, 372)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTeclaPresionada)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblAciertos)
                            .addComponent(jLabel4)
                            .addComponent(lblIntentos))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblrestante)
                        .addGap(19, 19, 19))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(599, Short.MAX_VALUE)
                    .addComponent(lblTiempo)
                    .addGap(17, 17, 17)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        //
    }//GEN-LAST:event_formKeyPressed

  //Evento que controla que se ha soltado una tecla
    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        //obtenemos la tecla presionada 
        char teclaPresionada = evt.getKeyChar();
         if(teclaPresionada == teclaSorteada) {
             aciertos++;
             lblAciertos.setText(aciertos + "");
         } else {
             intentos--;
             lblIntentos.setText(intentos + "");
         }
         //mostramos la tecla presionada debajo del panel principal
         String strTecla = Character.toString(teclaPresionada);
         strTecla = strTecla.toUpperCase();
         lblTeclaPresionada.setText(strTecla);
         
    }//GEN-LAST:event_formKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAciertos;
    private javax.swing.JLabel lblIntentos;
    private javax.swing.JLabel lblTecla;
    private javax.swing.JLabel lblTeclaPresionada;
    private javax.swing.JLabel lblTiempo;
    private javax.swing.JLabel lblrestante;
    // End of variables declaration//GEN-END:variables
}
